// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// EngineLayer is an autogenerated mock type for the EngineLayer type
type EngineLayer struct {
	mock.Mock
}

type EngineLayer_Expecter struct {
	mock *mock.Mock
}

func (_m *EngineLayer) EXPECT() *EngineLayer_Expecter {
	return &EngineLayer_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: ctx, key
func (_m *EngineLayer) Del(ctx context.Context, key string) error {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EngineLayer_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type EngineLayer_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *EngineLayer_Expecter) Del(ctx interface{}, key interface{}) *EngineLayer_Del_Call {
	return &EngineLayer_Del_Call{Call: _e.mock.On("Del", ctx, key)}
}

func (_c *EngineLayer_Del_Call) Run(run func(ctx context.Context, key string)) *EngineLayer_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *EngineLayer_Del_Call) Return(_a0 error) *EngineLayer_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EngineLayer_Del_Call) RunAndReturn(run func(context.Context, string) error) *EngineLayer_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, key
func (_m *EngineLayer) Get(ctx context.Context, key string) (string, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EngineLayer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type EngineLayer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *EngineLayer_Expecter) Get(ctx interface{}, key interface{}) *EngineLayer_Get_Call {
	return &EngineLayer_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *EngineLayer_Get_Call) Run(run func(ctx context.Context, key string)) *EngineLayer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *EngineLayer_Get_Call) Return(_a0 string, _a1 error) *EngineLayer_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *EngineLayer_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *EngineLayer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value
func (_m *EngineLayer) Set(ctx context.Context, key string, value string) error {
	ret := _m.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EngineLayer_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type EngineLayer_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
func (_e *EngineLayer_Expecter) Set(ctx interface{}, key interface{}, value interface{}) *EngineLayer_Set_Call {
	return &EngineLayer_Set_Call{Call: _e.mock.On("Set", ctx, key, value)}
}

func (_c *EngineLayer_Set_Call) Run(run func(ctx context.Context, key string, value string)) *EngineLayer_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *EngineLayer_Set_Call) Return(_a0 error) *EngineLayer_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EngineLayer_Set_Call) RunAndReturn(run func(context.Context, string, string) error) *EngineLayer_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewEngineLayer creates a new instance of EngineLayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEngineLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EngineLayer {
	mock := &EngineLayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
